

-- CREAR FUNCIÓN DE LIMPIEZA DE ENTEROS OPCION 1

CREATE OR REPLACE FUNCTION keepcoding.clean_integer(P_entero INT64) RETURNS INT64 AS
( (SELECT CASE WHEN P_entero IS NULL THEN -999999 ELSE P_entero END))

-- CREAR FUNCIÓN DE LIMPIEZA DE ENTEROS OPCION 2

CREATE OR REPLACE FUNCTION keepcoding.clean_integer(P_entero INT64) RETURNS INT64 AS
(
  IFNULL(P_entero, -999999)
)
